del *.obj /f /s /q 
del *.aps /f /s /q 
del *.opt /f /s /q 
del *.sbr /f /s /q 
del *.res /f /s /q 
del *.pdb /f /s /q 
del *.bsc /f /s /q 
del *.pch /f /s /q 
del *.ipch /f /s /q 
del *.idb /f /s /q 
del *.ncb /f /s /q 
del *.plg /f /s /q 
del *.ilk /f /s /q 
::del *.exe /f /s /q 
::del *.lib /f /s /q 
del *.nlb /f /s /q 
del *.sdf /f /s /q 
del *.exp /f /s /q 
del *.log /f /s /q 
del *.tlb /f /s /q 
del *.dep /f /s /q 
del *.suo /f /s /q 
del *.txt /f /s /q
del *.user /f /s /q 
del *.lastbuildstate /f /s /q 
del *.opensdf /f /s /q 
del BuildLogdel 
del *.htm /f /s /q 
del unsuccessfulbuild /f /s /q 
del *.tlog /f /s /q 
del *.log /f /s /q 
