# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = rtspPlayer
DESTDIR = ./Debug
CONFIG += debug
DEFINES += MARKUP_STL _STD_SMARTPTR WITH_OPENSSL WITH_DOM WITH_PURE_VIRTUAL
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(rtspPlayer.pri)
win32:RC_FILE = rtspPlayer.rc
